

on:
  push:
    branches:
      - main      # you can replace 'main' with the name of your branch
      - master

  pull_request:
    branches:
      - main      # you can replace 'main' with the name of your branch
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle
          check-latest: true

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Get test helper mockes
        run: dart run build_runner build

      - name: Run Flutter unit tests
        run: flutter test

      - name: build apk
        run: flutter build apk

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          ##notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}